version: '3.7'

services:

  postgres:
    image: postgres:15.2-alpine
    shm_size: 1g
    restart: always
    volumes:
      - .docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__NAME}
    ports:
      - ${POSTGRES__PORT}:${POSTGRES__PORT}
    hostname: ${POSTGRES__HOST}
    expose:
      - ${POSTGRES__PORT}

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"