version: '3.7'

services:
  postgres:
    image: postgres:15.2-alpine
    platform: linux/amd64
    shm_size: 1g
    restart: always
    ports:
      - ${POSTGRES__PROXY}:${POSTGRES__PORT}
    volumes:
      - .docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__NAME}
    healthcheck:
      test: pg_isready -d db_prod -U postgres
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  alembic:
    platform: linux/amd64
    build:
      dockerfile: docker/alembic.dockerfile
      context: ./
    volumes:
      - ./app:${VOLUME_MOUNT_PREFIX}/app
      - ./database:${VOLUME_MOUNT_PREFIX}/database
      - ./alembic:${VOLUME_MOUNT_PREFIX}/alembic
      - ./dictionaries:${VOLUME_MOUNT_PREFIX}/dictionaries
      - ./updater:${VOLUME_MOUNT_PREFIX}/updater
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    stdin_open: true

  rabbitmq:
    image: rabbitmq:3.13.2-management
    platform: linux/amd64
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
#    ports:
#      - ${RABBITMQ__WEB_PORT}:${RABBITMQ__WEB_PORT}

  agreemod:
    platform: linux/amd64
    build:
      dockerfile: docker/api.dockerfile
      context: ./
    ports:
      - ${API_PROXY}:${API_PORT}
    volumes:
      - ./app:${VOLUME_MOUNT_PREFIX}/app
      - ./database:${VOLUME_MOUNT_PREFIX}/database
      - ./dictionaries:${VOLUME_MOUNT_PREFIX}/dictionaries
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  updater:
    platform: linux/amd64
    build:
      dockerfile: docker/updater.dockerfile
      context: ./
    volumes:
      - ./updater:${VOLUME_MOUNT_PREFIX}/updater
      - ./database:${VOLUME_MOUNT_PREFIX}/database
      - ./dictionaries:${VOLUME_MOUNT_PREFIX}/dictionaries
      - ./rabbit:${VOLUME_MOUNT_PREFIX}/rabbit
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    platform: linux/amd64
    build:
      dockerfile: docker/telegram_bot.dockerfile
      context: ./
    volumes:
      - ./app:${VOLUME_MOUNT_PREFIX}/app
      - ./bot:${VOLUME_MOUNT_PREFIX}/bot
      - ./database:${VOLUME_MOUNT_PREFIX}/database
      - ./dictionaries:${VOLUME_MOUNT_PREFIX}/dictionaries
      - ./rabbit:${VOLUME_MOUNT_PREFIX}/rabbit

  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          if [ "$$(date +'%H:%M')" = '00:00' ]; then
            docker restart updater
          fi
          sleep 60
        done