"""add new column in arival and badge

Revision ID: 2024_04_03_1604
Revises: 2024_04_03_1549
Create Date: 2024-04-03 16:04:33.038772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2024_04_03_1604"
down_revision: Union[str, None] = "2024_04_03_1549"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "arrival",
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "badge",
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("badge", "last_updated")
    op.drop_column("arrival", "last_updated")
    # ### end Alembic commands ###
