"""change int id to notion_id in anons

Revision ID: 5661c2563d6a
Revises: 081e327b9a8a
Create Date: 2024-06-11 18:44:48.951052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5661c2563d6a'
down_revision: Union[str, None] = '081e327b9a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_badges', sa.Column('notion_id', sa.UUID(), nullable=False))
    op.drop_column('anonymous_badges', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_badges', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('anonymous_badges', 'notion_id')
    # ### end Alembic commands ###
