"""init

Revision ID: 0bfcc405c30e
Revises: 
Create Date: 2024-03-07 17:47:41.869430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfcc405c30e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_color',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_badge_color'))
    )
    op.create_table('direction_type',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_federal', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_direction_type'))
    )
    op.create_table('participation_type',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_participation_type'))
    )
    op.create_table('person',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('other_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('diet', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('notion_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('notion_id', name=op.f('pk_person'))
    )
    op.create_table('direction',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('first_year', sa.Integer(), nullable=True),
    sa.Column('last_year', sa.Integer(), nullable=True),
    sa.Column('notion_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['direction_type.code'], name=op.f('fk_direction_type_direction_type')),
    sa.PrimaryKeyConstraint('notion_id', name=op.f('pk_direction'))
    )
    op.create_table('participation_role',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('badge_color', sa.String(), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('is_team', sa.Boolean(), nullable=False),
    sa.Column('is_free_feed', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['badge_color'], ['badge_color.code'], name=op.f('fk_participation_role_badge_color_badge_color')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_participation_role'))
    )
    op.create_table('badge',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('infant', sa.Boolean(), nullable=True),
    sa.Column('diet', sa.String(), nullable=True),
    sa.Column('feed', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('participation_code', sa.String(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('direction_id', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('notion_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.notion_id'], name=op.f('fk_badge_direction_id_direction')),
    sa.ForeignKeyConstraint(['participation_code'], ['participation_type.code'], name=op.f('fk_badge_participation_code_participation_type')),
    sa.ForeignKeyConstraint(['person_id'], ['person.notion_id'], name=op.f('fk_badge_person_id_person')),
    sa.ForeignKeyConstraint(['role_code'], ['participation_role.code'], name=op.f('fk_badge_role_code_participation_role')),
    sa.PrimaryKeyConstraint('notion_id', name=op.f('pk_badge')),
    sa.UniqueConstraint('number', name=op.f('uq_badge_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge')
    op.drop_table('participation_role')
    op.drop_table('direction')
    op.drop_table('person')
    op.drop_table('participation_type')
    op.drop_table('direction_type')
    op.drop_table('badge_color')
    # ### end Alembic commands ###
