"""populate status

Revision ID: ef9c8d0cde2c
Revises: bdd9c6f1f320
Create Date: 2024-05-30 00:06:00.569958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from app.db.dictionaries_orm import ParticipationStatusAppORM


# revision identifiers, used by Alembic.
revision: str = 'ef9c8d0cde2c'
down_revision: Union[str, None] = 'bdd9c6f1f320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = orm.Session(bind=op.get_bind())
    session.add_all(ParticipationStatusAppORM.fill_table())
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
