"""badge batch and number now nullable

Revision ID: 3c0771f4924c
Revises: 20c2bd0882d4
Create Date: 2024-06-13 18:31:20.524114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0771f4924c'
down_revision: Union[str, None] = '20c2bd0882d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badge', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('badge', 'batch',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badge', 'batch',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('badge', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
