"""update participation role

Revision ID: 118d7eb37b10
Revises: da891e1e7ce0
Create Date: 2024-05-31 17:34:51.691885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm, text

# revision identifiers, used by Alembic.
revision: str = '118d7eb37b10'
down_revision: Union[str, None] = 'da891e1e7ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = orm.Session(bind=op.get_bind())
    session.execute(text("TRUNCATE TABLE participation_role CASCADE"))
    op.add_column('participation_role', sa.Column('color', sa.String(), nullable=False))
    op.add_column('participation_role', sa.Column('notion_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_participation_role_color_badge_color'), 'participation_role', 'badge_color', ['color'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_participation_role_color_badge_color'), 'participation_role', type_='foreignkey')
    op.drop_column('participation_role', 'notion_id')
    op.drop_column('participation_role', 'color')
    # ### end Alembic commands ###
