"""add occupation to badge

Revision ID: 914cf367f5c0
Revises: ef9c8d0cde2c
Create Date: 2024-05-30 16:12:29.403348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914cf367f5c0'
down_revision: Union[str, None] = 'ef9c8d0cde2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('occupation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'occupation')
    # ### end Alembic commands ###
