"""populate participation role

Revision ID: b97198c275b0
Revises: 118d7eb37b10
Create Date: 2024-05-31 17:42:51.996767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from updater.src.db.orm.dictionaries_orm import ParticipationRoleAppORM

# revision identifiers, used by Alembic.
revision: str = 'b97198c275b0'
down_revision: Union[str, None] = '118d7eb37b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = orm.Session(bind=op.get_bind())
    #TODO: Move filling ParticipationRole table to the endpoint
    #session.add_all(ParticipationRoleAppORM.fill_table())
    session.commit()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
