"""logs row_id now nullable

Revision ID: 6aa4fb4cc8bc
Revises: 3c0771f4924c
Create Date: 2024-06-13 18:59:42.213426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa4fb4cc8bc'
down_revision: Union[str, None] = '3c0771f4924c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'row_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'row_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
