"""fix badge foreign key

Revision ID: 3266bc37a54d
Revises: 914cf367f5c0
Create Date: 2024-05-30 17:47:25.745882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3266bc37a54d'
down_revision: Union[str, None] = '914cf367f5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_badge_person_id_person', 'badge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_badge_person_id_person'), 'badge', 'person', ['person_id'], ['notion_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_badge_person_id_person'), 'badge', type_='foreignkey')
    op.create_foreign_key('fk_badge_person_id_person', 'badge', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###
