"""coda_index is nullable

Revision ID: 2fcf79b2b6fa
Revises: 6aa4fb4cc8bc
Create Date: 2024-06-13 22:46:06.508431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcf79b2b6fa'
down_revision: Union[str, None] = '6aa4fb4cc8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arrival', 'coda_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arrival', 'coda_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
