"""COMMENT

Revision ID: 2024_06_30_1911
Revises: 5ed19b1a2be2
Create Date: 2024-06-30 19:11:34.325062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2024_06_30_1911'
down_revision: Union[str, None] = '5ed19b1a2be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('badge', sa.Column('child', sa.Boolean(), nullable=True))
    op.drop_constraint('fk_badge_infant_id_badge', 'badge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_badge_parent_id_badge'), 'badge', 'badge', ['parent_id'], ['notion_id'], ondelete='CASCADE')
    op.drop_column('badge', 'infant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('infant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_badge_parent_id_badge'), 'badge', type_='foreignkey')
    op.create_foreign_key('fk_badge_infant_id_badge', 'badge', 'badge', ['infant_id'], ['notion_id'], ondelete='CASCADE')
    op.drop_column('badge', 'child')
    op.drop_column('badge', 'parent_id')
    # ### end Alembic commands ###
