"""populate_dicts

Revision ID: 606a14968f4e
Revises: 0bfcc405c30e
Create Date: 2024-03-07 17:50:21.267237

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import orm

from alembic import op
from app.db.orm import (
    BadgeColorAppORM,
    DirectionTypeAppORM,
    ParticipationRoleAppORM,
    ParticipationTypeAppORM,
)

# revision identifiers, used by Alembic.
revision: str = "606a14968f4e"
down_revision: Union[str, None] = "0bfcc405c30e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = orm.Session(bind=op.get_bind())
    session.add_all(BadgeColorAppORM.fill_table())
    session.add_all(DirectionTypeAppORM.fill_table())
    session.add_all(ParticipationRoleAppORM.fill_table())
    session.add_all(ParticipationTypeAppORM.fill_table())
    session.commit()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
