"""change coda_index

Revision ID: e15e5fc0a581
Revises: 2d6cfef184fd
Create Date: 2024-06-23 14:49:45.959170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm, sql

# revision identifiers, used by Alembic.
revision: str = 'e15e5fc0a581'
down_revision: Union[str, None] = '2d6cfef184fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'coda_index',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    session = orm.Session(bind=op.get_bind())
    session.execute(sql.text("""TRUNCATE TABLE public.participation cascade"""))
    session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'coda_index',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
