"""init

Revision ID: 2024_02_25_1614
Revises: 
Create Date: 2024-02-25 16:14:47.951030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024_02_25_1614'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('first_year', sa.Integer(), nullable=True),
    sa.Column('last_year', sa.Integer(), nullable=True),
    sa.Column('notion_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('notion_id', name=op.f('pk_direction'))
    )
    op.create_table('person',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('other_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('diet', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('notion_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('notion_id', name=op.f('pk_person'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('direction')
    # ### end Alembic commands ###
