"""fix infant foreign key

Revision ID: 9874654430d5
Revises: 3edeccb80eb1
Create Date: 2024-06-01 13:19:58.015655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9874654430d5'
down_revision: Union[str, None] = '3edeccb80eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_badge_infant_id_badge', 'badge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_badge_infant_id_badge'), 'badge', 'badge', ['infant_id'], ['notion_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_badge_infant_id_badge'), 'badge', type_='foreignkey')
    op.create_foreign_key('fk_badge_infant_id_badge', 'badge', 'badge', ['infant_id'], ['id'])
    # ### end Alembic commands ###
