"""add cascade deletion

Revision ID: 2d6cfef184fd
Revises: ad56af5441ab
Create Date: 2024-06-21 10:17:53.376625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6cfef184fd'
down_revision: Union[str, None] = 'ad56af5441ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_arrival_badge_id_badge', 'arrival', type_='foreignkey')
    op.create_foreign_key(op.f('fk_arrival_badge_id_badge'), 'arrival', 'badge', ['badge_id'], ['notion_id'], ondelete='CASCADE')
    op.drop_constraint('fk_badge_infant_id_badge', 'badge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_badge_infant_id_badge'), 'badge', 'badge', ['infant_id'], ['notion_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_badge_infant_id_badge'), 'badge', type_='foreignkey')
    op.create_foreign_key('fk_badge_infant_id_badge', 'badge', 'badge', ['infant_id'], ['notion_id'])
    op.drop_constraint(op.f('fk_arrival_badge_id_badge'), 'arrival', type_='foreignkey')
    op.create_foreign_key('fk_arrival_badge_id_badge', 'arrival', 'badge', ['badge_id'], ['notion_id'])
    # ### end Alembic commands ###
