"""cleanup cyrillics

Revision ID: ad56af5441ab
Revises: 2fcf79b2b6fa
Create Date: 2024-06-19 13:40:58.120989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm, sql


# revision identifiers, used by Alembic.
revision: str = 'ad56af5441ab'
down_revision: Union[str, None] = '2fcf79b2b6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    session = orm.Session(bind=op.get_bind())
    session.execute(sql.text("""UPDATE badge SET diet = 'STANDARD' where diet in ('Без особенностей', 'без особенностей')"""))
    session.execute(sql.text("""UPDATE badge SET diet = 'VEGAN' where diet in ('Веган', 'веган')"""))
    session.execute(sql.text("""UPDATE badge SET feed = 'NO' where feed = 'Без питания'"""))
    session.execute(sql.text("""UPDATE badge SET feed = 'FREE' where feed = 'Бесплатно'"""))
    session.execute(sql.text("""UPDATE badge SET feed = 'PAID' where feed = 'Платно'"""))
    session.execute(sql.text("""UPDATE person SET diet = 'STANDARD' where diet in ('Без особенностей', 'без особенностей')"""))
    session.execute(sql.text("""UPDATE person SET diet = 'VEGAN' where diet in ('Веган', 'веган')"""))
    session.execute(sql.text("""UPDATE badge SET gender = 'MALE' where gender = 'мужской'"""))
    session.execute(sql.text("""UPDATE badge SET gender = 'FEMALE' where gender = 'женский'"""))
    session.execute(sql.text("""UPDATE badge SET gender = 'OTHER' where gender in ('другой', 'др.')"""))
    session.execute(sql.text("""UPDATE person SET gender = 'MALE' where gender = 'мужской'"""))
    session.execute(sql.text("""UPDATE person SET gender = 'FEMALE' where gender = 'женский'"""))
    session.execute(sql.text("""UPDATE person SET gender = 'OTHER' where gender in ('другой', 'др.')"""))
    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
