"""fix foreign keys

Revision ID: bdd9c6f1f320
Revises: 4d2ee9a59766
Create Date: 2024-05-29 23:26:33.237785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd9c6f1f320'
down_revision: Union[str, None] = '4d2ee9a59766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_arrival_badge_id_badge', 'arrival', type_='foreignkey')
    op.create_foreign_key(op.f('fk_arrival_badge_id_badge'), 'arrival', 'badge', ['badge_id'], ['notion_id'])
    op.drop_column('logs', 'row_id')
    op.add_column('logs', sa.Column('row_id', sa.UUID(), nullable=False))
    op.drop_constraint('fk_participation_direction_id_direction', 'participation', type_='foreignkey')
    op.drop_constraint('fk_participation_person_id_person', 'participation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participation_direction_id_direction'), 'participation', 'direction', ['direction_id'], ['notion_id'])
    op.create_foreign_key(op.f('fk_participation_person_id_person'), 'participation', 'person', ['person_id'], ['notion_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_participation_person_id_person'), 'participation', type_='foreignkey')
    op.drop_constraint(op.f('fk_participation_direction_id_direction'), 'participation', type_='foreignkey')
    op.create_foreign_key('fk_participation_person_id_person', 'participation', 'person', ['person_id'], ['id'])
    op.create_foreign_key('fk_participation_direction_id_direction', 'participation', 'direction', ['direction_id'], ['id'])
    op.drop_column('logs', 'row_id')
    op.add_column('logs', sa.Column('row_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(op.f('fk_arrival_badge_id_badge'), 'arrival', type_='foreignkey')
    op.create_foreign_key('fk_arrival_badge_id_badge', 'arrival', 'badge', ['badge_id'], ['id'])
    # ### end Alembic commands ###
