"""COMMENT

Revision ID: 2025_01_27_1806
Revises: 2024_06_30_1911
Create Date: 2025-01-27 18:06:40.873019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_01_27_1806'
down_revision: Union[str, None] = '2024_06_30_1911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Anonymous badges
    op.add_column('anonymous_badges', sa.Column('nocode_int_id', sa.Integer(), nullable=False))
    op.drop_column('anonymous_badges', 'notion_id')
    
    # Arrival (already following the correct pattern)
    op.add_column('arrival', sa.Column('badge_int_id', sa.Integer(), nullable=False))
    op.drop_column('arrival', 'badge_id')
    op.alter_column('arrival', 'badge_int_id',
               existing_type=sa.Integer(),
               new_column_name='badge_id')
    
    # Badge
    op.add_column('badge', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.add_column('badge', sa.Column('parent_int_id', sa.Integer(), nullable=True))
    op.add_column('badge', sa.Column('person_int_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_badge_parent_id_badge', 'badge', type_='foreignkey')
    op.drop_constraint('fk_badge_person_id_person', 'badge', type_='foreignkey')
    op.drop_column('badge', 'parent_id')
    op.drop_column('badge', 'person_id')
    op.alter_column('badge', 'parent_int_id',
               existing_type=sa.Integer(),
               new_column_name='parent_id')
    op.alter_column('badge', 'person_int_id',
               existing_type=sa.Integer(),
               new_column_name='person_id')
    op.drop_constraint('uq_badge_notion_id', 'badge', type_='unique')
    op.create_unique_constraint(op.f('uq_badge_nocode_int_id'), 'badge', ['nocode_int_id'])
    op.create_foreign_key(op.f('fk_badge_parent_id_badge'), 'badge', 'badge', ['parent_id'], ['nocode_int_id'], ondelete='CASCADE')
    op.drop_column('badge', 'notion_id')
    op.create_foreign_key(op.f('fk_arrival_badge_id_badge'), 'arrival', 'badge', ['badge_id'], ['nocode_int_id'], ondelete='CASCADE')
    
    # Badge directions
    op.add_column('badge_directions', sa.Column('badge_int_id', sa.Integer(), nullable=False))
    op.add_column('badge_directions', sa.Column('direction_int_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_badge_directions_badge_id_badge', 'badge_directions', type_='foreignkey')
    op.drop_constraint('fk_badge_directions_direction_id_direction', 'badge_directions', type_='foreignkey')
    op.drop_column('badge_directions', 'badge_id')
    op.drop_column('badge_directions', 'direction_id')
    op.alter_column('badge_directions', 'badge_int_id',
               existing_type=sa.Integer(),
               new_column_name='badge_id')
    op.alter_column('badge_directions', 'direction_int_id',
               existing_type=sa.Integer(),
               new_column_name='direction_id')
    op.create_foreign_key(op.f('fk_badge_directions_badge_id_badge'), 'badge_directions', 'badge', ['badge_id'], ['nocode_int_id'], onupdate='CASCADE', ondelete='CASCADE')

    # Direction
    op.add_column('direction', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_participation_direction_id_direction', 'participation', type_='foreignkey')
    op.drop_constraint('fk_participation_person_id_person', 'participation', type_='foreignkey')
    op.drop_constraint('uq_direction_notion_id', 'direction', type_='unique')
    op.create_unique_constraint(op.f('uq_direction_nocode_int_id'), 'direction', ['nocode_int_id'])
    op.drop_column('direction', 'notion_id')
    op.create_foreign_key(op.f('fk_badge_directions_direction_id_direction'), 'badge_directions', 'direction', ['direction_id'], ['nocode_int_id'], onupdate='CASCADE')

    # Participation
    op.add_column('participation', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.add_column('participation', sa.Column('person_int_id', sa.Integer(), nullable=False))
    op.add_column('participation', sa.Column('direction_int_id', sa.Integer(), nullable=False))
    op.drop_column('participation', 'person_id')
    op.drop_column('participation', 'direction_id')
    op.alter_column('participation', 'person_int_id',
               existing_type=sa.Integer(),
               new_column_name='person_id')
    op.alter_column('participation', 'direction_int_id',
               existing_type=sa.Integer(),
               new_column_name='direction_id')
    op.drop_constraint('uq_participation_notion_id', 'participation', type_='unique')
    op.create_unique_constraint(op.f('uq_participation_nocode_int_id'), 'participation', ['nocode_int_id'])
    op.create_foreign_key(op.f('fk_participation_direction_id_direction'), 'participation', 'direction', ['direction_id'], ['nocode_int_id'])
    op.drop_column('participation', 'notion_id')

    # Person
    op.add_column('person', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_person_notion_id', 'person', type_='unique')
    op.create_unique_constraint(op.f('uq_person_nocode_int_id'), 'person', ['nocode_int_id'])
    op.drop_column('person', 'notion_id')
    op.create_foreign_key(op.f('fk_badge_person_id_person'), 'badge', 'person', ['person_id'], ['nocode_int_id'])
    op.create_foreign_key(op.f('fk_participation_person_id_person'), 'participation', 'person', ['person_id'], ['nocode_int_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('notion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_person_nocode_int_id'), 'person', type_='unique')
    op.create_unique_constraint('uq_person_notion_id', 'person', ['notion_id'])
    op.drop_column('person', 'nocode_int_id')
    op.add_column('participation', sa.Column('notion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_participation_direction_id_direction'), 'participation', type_='foreignkey')
    op.drop_constraint(op.f('fk_participation_person_id_person'), 'participation', type_='foreignkey')
    op.create_foreign_key('fk_participation_person_id_person', 'participation', 'person', ['person_id'], ['notion_id'])
    op.create_foreign_key('fk_participation_direction_id_direction', 'participation', 'direction', ['direction_id'], ['notion_id'])
    op.drop_constraint(op.f('uq_participation_nocode_int_id'), 'participation', type_='unique')
    op.create_unique_constraint('uq_participation_notion_id', 'participation', ['notion_id'])
    op.alter_column('participation', 'direction_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('participation', 'person_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('participation', 'nocode_int_id')
    op.add_column('direction', sa.Column('notion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_direction_nocode_int_id'), 'direction', type_='unique')
    op.create_unique_constraint('uq_direction_notion_id', 'direction', ['notion_id'])
    op.drop_column('direction', 'nocode_int_id')
    op.drop_constraint(op.f('fk_badge_directions_badge_id_badge'), 'badge_directions', type_='foreignkey')
    op.drop_constraint(op.f('fk_badge_directions_direction_id_direction'), 'badge_directions', type_='foreignkey')
    op.create_foreign_key('fk_badge_directions_direction_id_direction', 'badge_directions', 'direction', ['direction_id'], ['notion_id'], onupdate='CASCADE')
    op.create_foreign_key('fk_badge_directions_badge_id_badge', 'badge_directions', 'badge', ['badge_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('badge_directions', 'direction_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('badge_directions', 'badge_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('badge', sa.Column('notion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_badge_parent_id_badge'), 'badge', type_='foreignkey')
    op.drop_constraint(op.f('fk_badge_person_id_person'), 'badge', type_='foreignkey')
    op.create_foreign_key('fk_badge_person_id_person', 'badge', 'person', ['person_id'], ['notion_id'])
    op.create_foreign_key('fk_badge_parent_id_badge', 'badge', 'badge', ['parent_id'], ['notion_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_badge_nocode_int_id'), 'badge', type_='unique')
    op.create_unique_constraint('uq_badge_notion_id', 'badge', ['notion_id'])
    op.alter_column('badge', 'person_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('badge', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('badge', 'nocode_int_id')
    op.drop_constraint(op.f('fk_arrival_badge_id_badge'), 'arrival', type_='foreignkey')
    op.create_foreign_key('fk_arrival_badge_id_badge', 'arrival', 'badge', ['badge_id'], ['notion_id'], ondelete='CASCADE')
    op.alter_column('arrival', 'badge_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('anonymous_badges', sa.Column('notion_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('anonymous_badges', 'nocode_int_id')
    # ### end Alembic commands ###

def bkp() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_badges', sa.Column('nocode_int_id', sa.Integer(), nullable=False))
    op.drop_column('anonymous_badges', 'notion_id')
    op.add_column('arrival', sa.Column('badge_int_id', sa.Integer(), nullable=False))
    op.drop_column('arrival', 'badge_id')
    op.alter_column('arrival', 'badge_int_id',
               existing_type=sa.Integer(),
               new_column_name='badge_id')
    op.drop_constraint('fk_arrival_badge_id_badge', 'arrival', type_='foreignkey')
    op.create_foreign_key(op.f('fk_arrival_badge_id_badge'), 'arrival', 'badge', ['badge_id'], ['nocode_int_id'], ondelete='CASCADE')
    op.add_column('badge', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.alter_column('badge', 'parent_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('badge', 'person_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('uq_badge_notion_id', 'badge', type_='unique')
    op.create_unique_constraint(op.f('uq_badge_nocode_int_id'), 'badge', ['nocode_int_id'])
    op.drop_constraint('fk_badge_parent_id_badge', 'badge', type_='foreignkey')
    op.drop_constraint('fk_badge_person_id_person', 'badge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_badge_person_id_person'), 'badge', 'person', ['person_id'], ['nocode_int_id'])
    op.create_foreign_key(op.f('fk_badge_parent_id_badge'), 'badge', 'badge', ['parent_id'], ['nocode_int_id'], ondelete='CASCADE')
    op.drop_column('badge', 'notion_id')
    op.alter_column('badge_directions', 'badge_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('badge_directions', 'direction_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('fk_badge_directions_badge_id_badge', 'badge_directions', type_='foreignkey')
    op.drop_constraint('fk_badge_directions_direction_id_direction', 'badge_directions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_badge_directions_direction_id_direction'), 'badge_directions', 'direction', ['direction_id'], ['nocode_int_id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('fk_badge_directions_badge_id_badge'), 'badge_directions', 'badge', ['badge_id'], ['nocode_int_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('direction', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_direction_notion_id', 'direction', type_='unique')
    op.create_unique_constraint(op.f('uq_direction_nocode_int_id'), 'direction', ['nocode_int_id'])
    op.drop_column('direction', 'notion_id')
    op.add_column('participation', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.alter_column('participation', 'person_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('participation', 'direction_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('uq_participation_notion_id', 'participation', type_='unique')
    op.create_unique_constraint(op.f('uq_participation_nocode_int_id'), 'participation', ['nocode_int_id'])
    op.drop_constraint('fk_participation_direction_id_direction', 'participation', type_='foreignkey')
    op.drop_constraint('fk_participation_person_id_person', 'participation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participation_person_id_person'), 'participation', 'person', ['person_id'], ['nocode_int_id'])
    op.create_foreign_key(op.f('fk_participation_direction_id_direction'), 'participation', 'direction', ['direction_id'], ['nocode_int_id'])
    op.drop_column('participation', 'notion_id')
    op.add_column('person', sa.Column('nocode_int_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_person_notion_id', 'person', type_='unique')
    op.create_unique_constraint(op.f('uq_person_nocode_int_id'), 'person', ['nocode_int_id'])
    op.drop_column('person', 'notion_id')
    # ### end Alembic commands ###