"""COMMENT

Revision ID: 2025_03_01_1838
Revises: 2025_03_01_1741
Create Date: 2025-03-01 15:38:39.626507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_03_01_1838'
down_revision: Union[str, None] = '2025_03_01_1741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_direction_type_name'), 'direction_type', ['name'])
    op.drop_constraint('fk_direction_type_direction_type', 'direction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_direction_type_direction_type'), 'direction', 'direction_type', ['type'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_direction_type_name'), 'direction_type', type_='unique')
    op.drop_constraint(op.f('fk_direction_type_direction_type'), 'direction', type_='foreignkey')
    op.create_foreign_key('fk_direction_type_direction_type', 'direction', 'direction_type', ['type'], ['code'])
    # ### end Alembic commands ###
