"""Ticket boolean field added to badges

Revision ID: 8d70087016ed
Revises: 58f88949e394
Create Date: 2025-06-13 15:13:07.953436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d70087016ed'
down_revision: Union[str, None] = '58f88949e394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('ticket', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'ticket')
    # ### end Alembic commands ###