"""COMMENT

Revision ID: 2025_03_01_1846
Revises: 2025_03_01_1838
Create Date: 2025-03-01 15:46:57.842305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_03_01_1846'
down_revision: Union[str, None] = '2025_03_01_1838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'status_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'status_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
