"""COMMENT

Revision ID: 2025_03_01_1903
Revises: 2025_03_01_1847
Create Date: 2025-03-01 16:03:33.039285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_03_01_1903'
down_revision: Union[str, None] = '2025_03_01_1847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
