"""COMMENT

Revision ID: 2025_03_27_0006
Revises: 2025_03_23_2030
Create Date: 2025-03-26 21:06:23.729070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_03_27_0006'
down_revision: Union[str, None] = '2025_03_23_2030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrival', sa.Column('nocode_int_id', sa.String(), nullable=True))
    op.drop_constraint('uq_arrival_coda_index', 'arrival', type_='unique')
    op.create_unique_constraint(op.f('uq_arrival_nocode_int_id'), 'arrival', ['nocode_int_id'])
    op.drop_column('arrival', 'coda_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrival', sa.Column('coda_index', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_arrival_nocode_int_id'), 'arrival', type_='unique')
    op.create_unique_constraint('uq_arrival_coda_index', 'arrival', ['coda_index'])
    op.drop_column('arrival', 'nocode_int_id')
    # ### end Alembic commands ###
