"""COMMENT

Revision ID: 2025_03_01_1847
Revises: 2025_03_01_1846
Create Date: 2025-03-01 15:47:27.775561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_03_01_1847'
down_revision: Union[str, None] = '2025_03_01_1846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'coda_index',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'coda_index',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
