"""add sync_state table

Revision ID: 969a79ceae2f
Revises: 5c9034d21357
Create Date: 2026-03-27 15:09:40.077067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969a79ceae2f'
down_revision: Union[str, None] = '5c9034d21357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_state',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('last_sync', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('table_name', name=op.f('pk_sync_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    # ### end Alembic commands ###
