"""add_column_other_names

Revision ID: 9f54f186369c
Revises: f30403a26584
Create Date: 2024-03-07 00:44:06.184899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f54f186369c'
down_revision: Union[str, None] = 'f30403a26584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('other_names', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'other_names')
    # ### end Alembic commands ###
