"""drop_other_names

Revision ID: f30403a26584
Revises: e9be6d966ab3
Create Date: 2024-03-07 00:43:10.077904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30403a26584'
down_revision: Union[str, None] = 'e9be6d966ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'other_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('other_names', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
