name: CI/CD - main & dev

on:
  push:
    branches:
      - dev
      - main
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'docker-compose.yml'
      - 'pyproject.toml'
      - 'alembic.ini'
      - 'alembic/**'
      - 'app/**'
      - 'bot/**'
      - 'database/**'
      - 'docker/**'
      - 'dictionaries/**'
      - 'rabbit/**'
      - 'updater/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          tmux new-session -d -s gh-actions-${{ github.ref_name }}
          tmux a -t gh-actions-${{ github.ref_name }}
          cd /deploy/agreemod-${{ github.ref_name }}/agreemod_v2
          git pull origin ${{ github.ref_name }}
          git checkout ${{ github.ref_name }}
          docker compose build
          docker compose down
          docker compose --project-name agreemod-${{ github.ref_name }} up -d
          docker update --restart always $(docker ps --filter "name=agreemod-${{ github.ref_name }}" -q)
